# Generated by Django 4.2 on 2023-04-09 14:38

import core.reinforce.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core_comment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reinforce",
            fields=[
                (
                    "comment_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core_comment.comment",
                    ),
                ),
                (
                    "source",
                    models.URLField(
                        max_length=250,
                        null=True,
                        validators=[
                            django.core.validators.URLValidator(schemes=["https"])
                        ],
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to=core.reinforce.models.upload_to
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core_comment.comment",),
        ),
    ]
