# Generated by Django 4.0 on 2023-05-03 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0002_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
