# Generated by Django 4.0 on 2023-05-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core_user', '0003_remove_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
