name: Build, Test and Deploy TIL backend

on:
  push:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Injecting environment vars
      run: |
        echo "${{ secrets.ENV_SECRETS }}" >> .env
    - name: Building Docker containers
      run: |
        sudo docker-compose up -d --build
        sudo docker-compose logs
    - name: Running Tests inside Docker containers
      run: |
        sudo docker-compose exec -T api pytest

  deploy:
    name: Deploying on VM via SSH
    if: ${{ github.event_name == 'push' }}
    needs: [build-test]
    runs-on: ubuntu-latest
    steps:
    - name: Deploying Application on VM
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_IP }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        script: |
          cd ~/
          ./docker-deploy.sh
